# Generated by Django 4.2.27 on 2025-12-26 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledMessage',
            fields=[
                ('scheduled_message_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=20)),
                ('message_type', models.CharField(choices=[('FEEDBACK', 'Feedback'), ('SURVEY', 'Survey'), ('OFFER', 'Offer'), ('REMINDER', 'Reminder')], max_length=20)),
                ('message_text', models.TextField()),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=10)),
                ('error', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_messages', to='clients.client')),
            ],
            options={
                'ordering': ['scheduled_at'],
            },
        ),
    ]
