# Generated by Django 4.2.27 on 2025-12-19 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RAGDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('PROFILE', 'Business Profile'), ('LOCATION', 'Location / Address'), ('TIMINGS', 'Business Timings'), ('SERVICES', 'Services / Categories'), ('POLICY', 'Policies'), ('FAQ', 'FAQ'), ('OTHER', 'Other')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rag_documents', to='clients.client')),
            ],
            options={
                'indexes': [models.Index(fields=['client', 'doc_type'], name='rag_ragdocu_client__8cdcea_idx')],
            },
        ),
    ]
