# Generated by Django 4.2.27 on 2025-12-18 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('whatsapp_number', models.CharField(max_length=20, unique=True)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faqs', models.BooleanField(default=True)),
                ('leads', models.BooleanField(default=True)),
                ('appointments', models.BooleanField(default=False)),
                ('orders', models.BooleanField(default=False)),
                ('payments', models.BooleanField(default=False)),
                ('sentiment', models.BooleanField(default=False)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
        ),
    ]
