# Generated by Django 4.2.27 on 2025-12-18 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conversationsession',
            unique_together={('client', 'user_phone')},
        ),
    ]
